src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuestionRepository", repositoryClass=QuestionRepository::class)
 * @Vich\Uploadable
 */
class Question
{

    const DIFFICULTY_LEVEL = [
        0 => 'Débutant',
        1 => 'Intermédiaire',
        2 => 'Avancé'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $label;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $explanation;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $is_available;

    /**
     * @Vich\UploadableField(mapping="question_image", fileNameProperty="imageName")
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Answer::class, mappedBy="question", cascade={"persist"})
     */
    private $answers;

    /**
     * @ORM\ManyToMany(targetEntity=Theme::class, inversedBy="questions")
     */
    private $themes;

    /**
     * @ORM\OneToMany(targetEntity=QuizQuestion::class, mappedBy="question")
     */
    private $quizQuestions;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $level;


    public function __construct()
    {
        // Initializing variables
        $this->level = 0;
        $this->is_available = false;
        $this->answers = new ArrayCollection();
        $this->quizQuestions = new ArrayCollection();
        $this->themes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getSlug() : string
    {
        return (new Slugify())->slugify($this->label);
    }

    public function getIsAvailable() : bool
    {
        return $this->is_available;
    }

    public function setIsAvailable(bool $is_available)
    {
        $this->is_available = $is_available;
    }

    /**
     * @param File|null $imageFile
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    /**
     * @return Collection|Answer[]
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->contains($answer)) {
            $this->answers->removeElement($answer);
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection
     */
    public function getThemes(): Collection
    {
        return $this->themes;
    }

    public function getThemesToString(): string
    {
        $result = "";
        foreach ($this->getThemes() as $i => $item)
        {
            $result = $result .  $item->getName();
            if ($i+1 < $this->getThemes()->count()){
                $result = $result . " - ";
            }
        }
        return $result;
    }

    public function addTheme(Theme $theme): self
    {
        if (!$this->themes->contains($theme)) {
            $this->themes[] = $theme;
        }

        return $this;
    }

    public function removeTheme(Theme $theme): self
    {
        if ($this->themes->contains($theme)) {
            $this->themes->removeElement($theme);
        }

        return $this;
    }

    public function getExplanation(): ?string
    {
        return $this->explanation;
    }

    public function setExplanation(?string $explanation): self
    {
        $this->explanation = $explanation;

        return $this;
    }

    /**
     * @return Collection|Quizquestion[]
     */
    public function getQuizQuestions(): Collection
    {
        return $this->quizQuestions;
    }

    public function addQuizQuestion(QuizQuestion $quizQuestions): self
    {
        if (!$this->quizQuestions->contains($quizQuestions)) {
            $this->quizQuestions[] = $quizQuestions;
            $quizQuestions->setQuestion($this);
        }

        return $this;
    }

    public function removeQuizQuestion(QuizQuestion $quizQuestions): self
    {
        if ($this->quizQuestions->contains($quizQuestions)) {
            $this->quizQuestions->removeElement($quizQuestions);
            // set the owning side to null (unless already changed)
            if ($quizQuestions->getQuestion() === $this) {
                $quizQuestions->setQuestion(null);
            }
        }

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getLevelDifficulty(): string {
        return self::DIFFICULTY_LEVEL[$this->level];
    }

    public static function getLevelChoices()
    {
        return array_flip(self::DIFFICULTY_LEVEL);
    }

    /**
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param mixed $updatedAt
     */
    public function setUpdatedAt($updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }


}

src/Form/QuestionType.php
<?php

namespace App\Form;

use App\Entity\Answer;
use App\Entity\Question;
use App\Entity\Theme;
use App\Repository\ThemeRepository;
use function PHPSTORM_META\type;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class QuestionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('label')
            ->add('explanation')
            ->add('is_available')
            ->add('level', ChoiceType::class, [
                'choices' => Question::getLevelChoices()
            ])
            ->add('themes', EntityType::class, [
                'class' => Theme::class,
                'choice_label' => 'name',
                'placeholder' => 'Choisir une option',
                'multiple' => true,
                'expanded' => true,
                'required' => false,
            ])
            ->add('imageFile', VichImageType::class, [
                'required' => false,
                'image_uri' => false,
                'download_uri' => false,
            ])
            ->add('answers', CollectionType::class, [
                'entry_type' => AnswerType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'by_reference' => false,
                'allow_delete' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Question::class,
        ]);
    }
}

src/Controller/QuestionController.php
<?php


namespace App\Controller;


use App\Entity\Question;
use App\Entity\QuestionSearch;
use App\Form\QuestionSearchType;
use App\Repository\AnswerRepository;
use App\Repository\QuestionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\Pagination\PaginationInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Twig\NodeVisitor\AbstractNodeVisitor;

class QuestionController extends AbstractController
{
    /**
     * @var QuestionRepository
     */
    private $repository;
    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(QuestionRepository $repository, EntityManagerInterface  $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/questions", name = "question.index")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request) : Response
    {
        $search = new QuestionSearch();
        $form = $this->createForm(QuestionSearchType::class, $search);
        $form->handleRequest($request);

        $questions = $paginator->paginate($this->repository->findAllQuery($search),
            $request->query->getInt('page', 1), /*page number*/
            12 /*limit per page*/);

        return $this->render('question/index.html.twig', [
                'questions' => $questions,
                'form'      => $form->createView()
            ]);
    }

    /**
     * @Route("/questions/{slug}-{id}", name="question.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Question $question
     * @param string $slug
     * @param AnswerRepository $answerRepository
     * @return Response
     */
    public function show(Question $question, string $slug, AnswerRepository $answerRepository) : Response
    {
        if ($question->getSlug() !== $slug)
        {
            return $this->redirectToRoute('question.show', [
                'id' => $question->getId(),
                'slug' => $question->getSlug()
            ], 301);
        }

        // Get the answers
        $answers = $answerRepository->findByQuestion($question->getId());

        return $this->render('question/show.html.twig', [
            'question' => $question,
            'answers' => $answers,
        ]);
    }

    /**
     * @Route("/questions/random", name="question.random")
     * @param QuestionRepository $questionRepository
     * @param AnswerRepository $answerRepository
     * @return Response
     */
    public function random(QuestionRepository $questionRepository, AnswerRepository $answerRepository) : Response
    {
        // Get a random question
        $question = $questionRepository->findRandomResultsQuery(1);

        // Get the answers
        $answers = $answerRepository->findByQuestion($question[0]->getId());

        return $this->render('question/show.html.twig', [
            'question' => $question[0],
            'answers' => $answers
        ]);
    }
}

templates/question/_question.html.twig
<div class="card">
    {% if question.imageName %}
        <img src="{{ vich_uploader_asset(question, 'imageFile') | imagine_filter('col4_thumb') }}" alt="card-img-top" style="width: 100%; height: auto">
    {% endif %}
   <div class="card-body">
       <h5 class="card-title">
           <a href="{{ path('question.show', {id: question.id, slug: question.slug}) }}">#{{ question.id }}</a>
       </h5>
       <p class="card-text"></p>
       <div>
           {% for theme in question.themes %}
               <span class="badge badge-pill badge-secondary">{{ theme.name }}</span>
           {% endfor %}
       </div>
       <div>
           {{ question.label }}</div>
       <div
               {% if question.getlevel == 0 %}
               class="text-info"
               {% elseif question.getlevel == 1 %}
               class="text-warning"
               {% elseif question.getlevel == 2 %}
               class="text-danger"
               {% endif %}
       >
           {{ question.getleveldifficulty }}
       </div>
   </div>
</div>

templates/question/index.html.twig
{% extends 'base.html.twig' %}

{% block body_header %}
    <div class="jumbotron">
        <div class="container">
            <h3>Filtrer les résultats :</h3>
            {{ form_start(form) }}
            <div class="row align-items-end">
                <div class="col-auto">
                    {{ form_label(form.levelMin, null, {errors: []}) }}
                </div>
                <div class="col-2">
                    {{ form_widget(form.levelMin) }}
                </div>
                {% if not form.vars.valid %}
                    <div class="col-auto">
                        {{ form_errors(form.levelMin) }}
                    </div>
                {% endif %}
                <div class="col-auto">
                    <button class="btn btn-primary">Rechercher</button>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block body %}

    <div class="container mt-4">
        <h2>Toutes les questions</h2>
        <div class="row flex">
            {% for question in questions %}
                <div class="col-3 mt-4">
                    {% include 'question/_question.html.twig' %}
                </div>
            {% endfor %}
        </div>

        {# display navigation #}
        <div class="navigation mt-4 d-flex justify-content-center">
            {{ knp_pagination_render(questions) }}
        </div>

    </div>

{% endblock %}

templates/question/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Question n° {{ question.id }}{% endblock %}

{% block body %}

    <div class="jumbotron">
        <div class="row">
            <div class="col ml-4">
                <h2>{{ question.label }}</h2>
            </div>
        </div>
    </div>

<div class="container mt-4">

    <div class="row flex">
        <div class="col-12 mt-4">
            <h4>Thème : {{ question.themesToString }}</h4>
            <h4>Difficulté : {{ question.getleveldifficulty }}</h4>
        </div>
    </div>

        <div class="card-body">

            {% for answer in answers %}
                <div class="row ml-3">
                    <div class="icon-column">
                        {% if answer.accuracy == 2 %}
                            <i class="fas fa-check"></i>
                        {% endif %}
                    </div>
                    <div class="col-auto">
                        {{ answer.label }}
                    </div>

                </div>
            {% endfor %}

            <p class="card-text">
                <br>
                {{ question.explanation }}
            </p>

        </div>

    </div>


</div>

{% endblock %}