src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuestionRepository", repositoryClass=QuestionRepository::class)
 * @Vich\Uploadable
 */
class Question
{

    const DIFFICULTY_LEVEL = [
        0 => 'Débutant',
        1 => 'Intermédiaire',
        2 => 'Avancé'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $label;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $explanation;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $is_available;

    /**
     * @Vich\UploadableField(mapping="question_image", fileNameProperty="imageName")
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Answer::class, mappedBy="question", cascade={"persist"})
     */
    private $answers;

    /**
     * @ORM\ManyToMany(targetEntity=Theme::class, inversedBy="questions")
     */
    private $themes;

    /**
     * @ORM\OneToMany(targetEntity=QuizQuestion::class, mappedBy="question")
     */
    private $quizQuestions;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $level;


    public function __construct()
    {
        // Initializing variables
        $this->level = 0;
        $this->is_available = false;
        $this->answers = new ArrayCollection();
        $this->quizQuestions = new ArrayCollection();
        $this->themes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getSlug() : string
    {
        return (new Slugify())->slugify($this->label);
    }

    public function getIsAvailable() : bool
    {
        return $this->is_available;
    }

    public function setIsAvailable(bool $is_available)
    {
        $this->is_available = $is_available;
    }

    /**
     * @param File|null $imageFile
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    /**
     * @return Collection|Answer[]
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->contains($answer)) {
            $this->answers->removeElement($answer);
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection
     */
    public function getThemes(): Collection
    {
        return $this->themes;
    }

    public function getThemesToString(): string
    {
        $result = "";
        foreach ($this->getThemes() as $i => $item)
        {
            $result = $result .  $item->getName();
            if ($i+1 < $this->getThemes()->count()){
                $result = $result . " - ";
            }
        }
        return $result;
    }

    public function addTheme(Theme $theme): self
    {
        if (!$this->themes->contains($theme)) {
            $this->themes[] = $theme;
        }

        return $this;
    }

    public function removeTheme(Theme $theme): self
    {
        if ($this->themes->contains($theme)) {
            $this->themes->removeElement($theme);
        }

        return $this;
    }

    public function getExplanation(): ?string
    {
        return $this->explanation;
    }

    public function setExplanation(?string $explanation): self
    {
        $this->explanation = $explanation;

        return $this;
    }

    /**
     * @return Collection|Quizquestion[]
     */
    public function getQuizQuestions(): Collection
    {
        return $this->quizQuestions;
    }

    public function addQuizQuestion(QuizQuestion $quizQuestions): self
    {
        if (!$this->quizQuestions->contains($quizQuestions)) {
            $this->quizQuestions[] = $quizQuestions;
            $quizQuestions->setQuestion($this);
        }

        return $this;
    }

    public function removeQuizQuestion(QuizQuestion $quizQuestions): self
    {
        if ($this->quizQuestions->contains($quizQuestions)) {
            $this->quizQuestions->removeElement($quizQuestions);
            // set the owning side to null (unless already changed)
            if ($quizQuestions->getQuestion() === $this) {
                $quizQuestions->setQuestion(null);
            }
        }

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getLevelDifficulty(): string {
        return self::DIFFICULTY_LEVEL[$this->level];
    }

    public static function getLevelChoices()
    {
        return array_flip(self::DIFFICULTY_LEVEL);
    }

    /**
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param mixed $updatedAt
     */
    public function setUpdatedAt($updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }


}

src/Entity/Quiz.php
<?php

namespace App\Entity;

use App\Repository\QuizRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuizRepository::class)
 */
class Quiz
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $score;

    /**
     * @ORM\Column(type="boolean", options={"default": true})
     */
    private $is_running;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;


    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="quizzes")
     */
    private $user;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $number;

    /**
     * @ORM\OneToMany(
     *     targetEntity=QuizQuestion::class,
     *     mappedBy="quiz",
     *     orphanRemoval=true),
     *     cascade={"persist"}
     */
    private $quizQuestions;

    public function __construct()
    {
        $this->score = 0;
        $this->is_running = true;
        $this->created_at = new \DateTime();
        $this->quizQuestions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getIsRunning(): ?bool
    {
        return $this->is_running;
    }

    public function setIsRunning(string $state): self
    {
        $this->is_running = $state;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|QuizQuestion[]
     */
    public function getQuizQuestions(): Collection
    {
        return $this->quizQuestions;
    }

    public function addQuizQuestion(QuizQuestion $quizQuestion): self
    {
        if (!$this->quizQuestions->contains($quizQuestion)) {
            $this->quizQuestions[] = $quizQuestion;
            $quizQuestion->setQuiz($this);
        }

        return $this;
    }

    public function removeQuizQuestion(QuizQuestion $quizQuestion): self
    {
        if ($this->quizQuestions->contains($quizQuestion)) {
            $this->quizQuestions->removeElement($quizQuestion);
            // set the owning side to null (unless already changed)
            if ($quizQuestion->getQuiz() === $this) {
                $quizQuestion->setQuiz(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * @param mixed $number
     */
    public function setNumber($number): void
    {
        $this->number = $number;
    }

    /**
     * @return mixed
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * @param mixed $score
     */
    public function setScore($score): void
    {
        $this->score = $score;
    }

    /**
     * Add some points to the score
     *
     * @param $points
     */
    public function addScore($points): void
    {
        $this->score += $points;
    }

    /**
     * Get all the themes corresponding to the quiz without repetition
     *
     * @return string
     */
    public function getThemes() : string
    {
        $themes = array();

        // For each quizQuestion item, get the corresponding themes if not already listed
        foreach ($this->quizQuestions as $quizQuestion){
            foreach ($quizQuestion->getQuestion()->getThemes() as $theme) {
                $themeName = $theme->getName();
                if (!in_array($themeName, $themes)) {
                    $themes[] = $themeName;
                }
            }
        }

        // Return the themes as a string
        return implode($themes, ", ");

    }
}

src/Form/QuizType.php
<?php

namespace App\Form;

use App\Entity\Question;
use App\Entity\Quiz;
use App\Entity\QuizQuestion;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuizType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('created_at')
            ->add('updated_at')
            ->add('is_running');
           // ->add('user');/*
           /*->add('quizquestions', CollectionType::class, [
               'entry_type' => QuizQuestionType::class,
               'entry_options' => ['label' => false],
               'allow_add' => true,
               'by_reference' => false,
               'allow_delete' => true,
           ]);*/



        /*$builder->add('quizquestions', EntityType::class, [
            'class' => QuizQuestion::class,
            'query_builder' => function (EntityRepository $er) {
                return $er->createQueryBuilder('q');
                    //->where('q.id IN(:question_ids)')
                    //->setParameter('question_ids', '');
            },
            'choice_label' => 'username',
        ]);*/
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Quiz::class,
        ]);
    }
}

templates/quiz/_quizquestion.html.twig
<div
        {% if quizQuestion.answer.accuracy == 0 %}
            class="card border-danger"
        {% elseif quizQuestion.answer.accuracy == 1 %}
            class="card border-warning"
        {% elseif quizQuestion.answer.accuracy == 2 %}
            class="card border-success"
        {% endif %}

>

    <div {% if quizQuestion.answer.accuracy == 0 %}
            class="card-header bg-danger"
        {% elseif quizQuestion.answer.accuracy == 1 %}
            class="card-header bg-warning"
        {% elseif quizQuestion.answer.accuracy == 2 %}
            class="card-header bg-success"
            {% endif %}>

    </div>

    <div class="card-body">

        <h5 class="card-title">
            {{ quizQuestion.question.label }}
        </h5>

        {#<div
                {% if quizQuestion.question.getlevel == 0 %}
                    class="text-info"
                {% elseif quizQuestion.question.getlevel == 1 %}
                    class="text-warning"
                {% elseif quizQuestion.question.getlevel == 2 %}
                    class="text-danger"
                {% endif %}
        >
            {{ quizQuestion.question.levelDifficulty }}
        </div>#}

        <p class="card-text">
            {{ quizQuestion.question.explanation }}
        </p>


        {% for answer in quizQuestion.question.answers %}
        <div class="row ml-3">
            <div class="icon-column">
                {% if answer == quizQuestion.answer %}
                    {% if answer.accuracy == 0 %}
                        <i class="fas fa-times"></i>
                    {% elseif answer.accuracy == 1 %}
                        <i class="fas fa-minus"></i>
                    {% elseif answer.accuracy == 2 %}
                        <i class="fas fa-check"></i>
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-auto">
                {{ answer.label }}
            </div>

        </div>
        {% endfor %}

        {#<p class="card-text">
            {% for theme in quizQuestion.question.themes %}
                <span class="badge badge-pill badge-secondary">{{ theme.name }}</span>
            {% endfor %}
        </p>#}
    </div>

    <div class="card-footer">
        {% for theme in quizQuestion.question.themes %}
                <span class="badge badge-pill badge-secondary">{{ theme.name }}</span>
            {% endfor %}
    </div>

</div>

templates/quiz/result.html.twig
{% extends 'base.html.twig' %}

{% block body_header %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-9">
                    <h3>Résultats du quizz #{{ quiz.number }} </h3>
                </div>
                <div class="col-3 text-right">
                    <h1><i class="fas fa-trophy"></i> {{ quiz.score }}/10 </h1>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <a href="{{ path ('quiz.results') }}" class="btn btn-node">Voir tous mes résultats</a>
                </div>
            </div>
            {#
            {{ form_start(form) }}
            <div class="row align-items-end">
                <div class="col-auto">
                    {{ form_label(form.levelMin, null, {errors: []}) }}
                </div>
                <div class="col-2">
                    {{ form_widget(form.levelMin) }}
                </div>
                {% if not form.vars.valid %}
                    <div class="col-auto">
                        {{ form_errors(form.levelMin) }}
                    </div>
                {% endif %}
                <div class="col-auto">
                    <button class="btn btn-primary">Rechercher</button>
                </div>
            </div>
            {{ form_end(form) }}#}

        </div>
    </div>
{% endblock %}

{% block body %}

    <div class="container mt-4">
        <div class="row flex">
            {% for quizQuestion in quizQuestions %}
                <div class="col-12 mt-4">
                    {% include 'quiz/_quizquestion.html.twig' %}
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}

templates/quiz/results.html.twig
{% extends 'base.html.twig' %}

{% block body_header %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h3>Mes résultats :</h3>
                </div>
                <div class="col text-right">
                    <h3>
                        <i class="fas fa-trophy bronze-medal"></i> {{ trophies['bronze'] }}
                        <i class="fas fa-trophy silver-medal"></i> {{ trophies['silver'] }}
                        <i class="fas fa-trophy gold-medal"></i> {{ trophies['gold'] }}
                    </h3>
                </div>
            </div>

            {#
            {{ form_start(form) }}
            <div class="row align-items-end">
                <div class="col-auto">
                    {{ form_label(form.levelMin, null, {errors: []}) }}
                </div>
                <div class="col-2">
                    {{ form_widget(form.levelMin) }}
                </div>
                {% if not form.vars.valid %}
                    <div class="col-auto">
                        {{ form_errors(form.levelMin) }}
                    </div>
                {% endif %}
                <div class="col-auto">
                    <button class="btn btn-primary">Rechercher</button>
                </div>
            </div>
            {{ form_end(form) }}#}
        </div>
    </div>
{% endblock %}

{% block body %}

    <div class="container mt-4">
        <h2>Mes quizz</h2>

        {% if quizzes is empty %}
            <div class="row">
                <div class="col-9">
                    <h4>
                        Vous n'avez aucun résultat !
                    </h4>
                </div>
                <div class="col-3">
                    <a href="{{ path ('quiz.new') }}" class="btn btn-node">Nouveau quizz</a>
                </div>
            </div>

        {% else %}

            <table class="table table-striped">
                <thead>
                    <tr>
                        <td>#</td>
                        <td>Thèmes associés <i class="fas fa-tag"></i></td>
                        <td>Score <i class="fas fa-trophy"></i></td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                {% for quiz in quizzes %}
                    <tr>
                        <td class="align-middle">{{ quiz.number }}</td>
                        <td class="align-middle">{{ quiz.themes }}</td>
                        <td class="align-middle">
                            <span
                                        {% if quiz.score == 10 %}
                                    class="gold-medal"
                                {% elseif quiz.score >= 8 %}
                                    class="silver-medal"
                                {% elseif quiz.score >= 6 %}
                                    class="bronze-medal"
                                        {% endif %}>{{ quiz.score }}</span></td>
                        <td class="align-middle">
                            {% if quiz.isRunning %}
                                <a href="{{ path ('quiz.play', {id: quiz.id}) }}" class="btn btn-node">Reprendre le quizz</a>
                            {% else %}
                                <a href="{{ path ('quiz.result', {id: quiz.id}) }}" class="btn btn-node">Voir le quizz</a>

                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            {# display navigation #}
            <div class="navigation mt-4 d-flex justify-content-center">
                {{ knp_pagination_render(quizzes) }}
            </div>

        {% endif %}

    </div>

{% endblock %}

templates/quiz/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Question n° {% endblock %}

{% block body %}

    <div class="jumbotron">
        <div class="row">
            <div class="col md-9">
                <h1>Quiz n°{{ quizquestion.quiz.number }} </h1>
                <h2>Question {{ quizquestion.number }}</h2>
            </div>
            <div class="col-md-3">
                    {% if quizquestion.question.imageName is not null  %}
                        <img src="{{ vich_uploader_asset(quizquestion.question, 'imageFile') | imagine_filter('quiz_thumb') }}" alt="card-img-top" style="width: 100%; height: auto">
                    {% endif %}
            </div>
        </div>
    </div>

<div class="container mt-4">

    {% if not form.vars.valid %}
        <ul>
            {# Loop through every form item #}
            {% for child in form.children %}
                {# Display the errors of the form item #}
                {%for error in child.vars.errors%}
                    <li>{{error.message}}</li>
                {%endfor%}
            {%endfor%}
        </ul>
    {%endif%}


    <div class="row">
        <div class="col">

            {#<h2>Quiz
                {{ quizquestion.quiz.id}}
                Question
                {{ quizquestion.question.id }}
                QuizQuestion
                {{ quizquestion.id}}

            </h2>#}
                <p>{{ quizquestion.question.label }}</p>

            {{ form_start(form) }}

            <button class="btn btn-node float-right">Valider</button>


            {{ form_end(form) }}
        </div>
    </div>



    <nav class="nav nav-bars mb-4"></nav>
</div>

{% endblock %}